,>++++++++[<-------->-]   (read1)
,>++++++++[<-------->-]   (read2)
[->+>+<<]                (duplicate)
>>[-<<+>>]               (move)
<<[->+>>+<<<<]           (prepare to add)
>>>>[<<+>>-]             (actual addition)
<<<                     (return to starting point)
<<<<<<.                 (print the sum)
