>,          (read first number)
>,          (read second number)
[->++<]     (double first number)
>[-         (decrease second number and add it to the doubled first number)
  >[-<+>]   (add to the next cell)
<-]         (loop ends when second number reaches 0)
<           (move to the first cell)
++++++++++  (create a reference cell with value 10 for newline)
>[->++<]    (double it to get value 20)
>>+.        (print newline)
<<<<.       (print the sum)
